settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: my-echo-example
    path: .
    commands:
      install:
        status: true
      build:
        status: true
      run:
        status: true
    watcher:
      extensions:
        - go
      paths:
        - /
      ignore_paths:
        - vendor
        - .git
