settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: host-reload-sample
    path: .
    commands:
      install:
        status: true
      run:
        status: true
    watcher:
      extensions:
        - go
      paths: // watched paths
        - /
      ignore_paths:  // ignored paths
        - vendor
        - .git
